# Generated by Django 2.2.5 on 2019-09-10 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(blank=True, choices=[(None, 'Fakülte Seçiniz'), ('dis_hekimligi', 'Diş Hekimliği Fakültesi'), ('ezcacilik', 'Eczacılık Fakültesi'), ('edebiyat', 'Edebiyat Fakültesi'), ('egitim', 'Eğitim Fakültesi'), ('fen', 'Fen Fakültesi'), ('guzel_sanatlar', 'Güzel Sanatlar, Tasarım ve Mimarlık Fakültesi'), ('hemsirelik', 'Hemşirelik Fakültesi'), ('iibf', 'İktasi ve İdari Bilimler Fakültesi'), ('iletisim', 'İletişim Fakültesi'), ('muhendislik', 'Mühendislik Fakültesi'), ('saglik_bilimleri', 'Sağlık Bilimleri Fakültesi'), ('spor_bilimleri', 'Spor Bilimleri Fakültesi'), ('su_urunleri', 'Su Ürünleri Fakültesi'), ('tip', 'Tıp Fakültesi'), ('ziraat', 'Ziraat Fakültesi')], max_length=6, null=True, verbose_name='Fakülteniz:')),
                ('phone_number', models.CharField(blank=True, help_text='Notifications will send to your phone number.', max_length=10, null=True, verbose_name='Telefon Numaranız:')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Profiller',
            },
        ),
    ]
