# Generated by Django 2.2.5 on 2019-09-11 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='faculty',
            field=models.CharField(blank=True, choices=[(None, 'Fakülte Seçiniz'), ('dis_hekimligi', 'Diş Hekimliği Fakültesi'), ('ezcacilik', 'Eczacılık Fakültesi'), ('edebiyat', 'Edebiyat Fakültesi'), ('egitim', 'Eğitim Fakültesi'), ('fen', 'Fen Fakültesi'), ('guzel_sanatlar', 'Güzel Sanatlar, Tasarım ve Mimarlık Fakültesi'), ('hemsirelik', 'Hemşirelik Fakültesi'), ('iibf', 'İktasi ve İdari Bilimler Fakültesi'), ('iletisim', 'İletişim Fakültesi'), ('muhendislik', 'Mühendislik Fakültesi'), ('saglik_bilimleri', 'Sağlık Bilimleri Fakültesi'), ('spor_bilimleri', 'Spor Bilimleri Fakültesi'), ('su_urunleri', 'Su Ürünleri Fakültesi'), ('tip', 'Tıp Fakültesi'), ('ziraat', 'Ziraat Fakültesi')], max_length=6, null=True, verbose_name='Fakültesi:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Notifications will send to your phone number.', max_length=10, null=True, verbose_name='Telefon Numarası:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
