# Generated by Django 2.2.5 on 2019-09-17 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20190915_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Selling Requests'},
        ),
        migrations.AlterModelOptions(
            name='paymentnotification',
            options={'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='contact',
            field=models.CharField(choices=[(None, 'Choose an option'), ('wMail', 'Contact me with e-mail'), ('wPhone', 'Contact me with phone number')], help_text="*We'll use your saved contact information. To check, click 'My Profile'", max_length=100, null=True, verbose_name='Contact:'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='department',
            field=models.CharField(help_text="Note's department.", max_length=200, null=True, verbose_name='Department:'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='faculty',
            field=models.CharField(choices=[(None, 'Choose a faculty'), ('dentistry', 'Faculty of Dentistry'), ('pharmacy', 'Faculty of Pharmacy'), ('literature', 'Faculty of Literature'), ('educational', 'Faculty of Educational Sciences'), ('science', 'Faculty of Sciences'), ('arts', 'Faculty of Arts'), ('health', 'Faculty of Health Science'), ('seas', 'School of Economics and Administrative Sciences'), ('engineering', 'Faculty of Engineering'), ('medical', 'Medical Faculty'), ('law', 'Faculty of Law')], max_length=100, null=True, verbose_name='Faculty:'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='lecture',
            field=models.CharField(help_text="Note's lecture.", max_length=200, null=True, verbose_name='Lecture:'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='note',
            field=models.TextField(blank=True, help_text='Any information that we need to know.', max_length=1000, null=True, verbose_name='Extra note:'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='page',
            field=models.CharField(max_length=200, null=True, verbose_name='Page number:'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User:'),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='bought_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='note.EgeNote', verbose_name='Want to buy:'),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User:'),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='who_send',
            field=models.CharField(help_text='*Please enter paying account owner.*', max_length=100, null=True, verbose_name='Who paid (account owner):'),
        ),
    ]
