# Generated by Django 2.2.5 on 2019-09-14 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EgeNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(choices=[(None, 'Fakülte Seçiniz'), ('dis_hekimligi', 'Diş Hekimliği Fakültesi'), ('ezcacilik', 'Eczacılık Fakültesi'), ('edebiyat', 'Edebiyat Fakültesi'), ('egitim', 'Eğitim Fakültesi'), ('fen', 'Fen Fakültesi'), ('guzel_sanatlar', 'Güzel Sanatlar, Tasarım ve Mimarlık Fakültesi'), ('hemsirelik', 'Hemşirelik Fakültesi'), ('iibf', 'İktasi ve İdari Bilimler Fakültesi'), ('iletisim', 'İletişim Fakültesi'), ('muhendislik', 'Mühendislik Fakültesi'), ('saglik_bilimleri', 'Sağlık Bilimleri Fakültesi'), ('spor_bilimleri', 'Spor Bilimleri Fakültesi'), ('su_urunleri', 'Su Ürünleri Fakültesi'), ('tip', 'Tıp Fakültesi'), ('ziraat', 'Ziraat Fakültesi')], max_length=100, null=True, verbose_name='Fakülte:')),
                ('department', models.CharField(help_text='Notun hangi bölüme ait olduğunu yazınız.', max_length=200, null=True, verbose_name='Bölüm:')),
                ('lecture', models.CharField(help_text='Notun hangi derse ait olduğunu yazınız.', max_length=200, null=True, verbose_name='Ders:')),
                ('page', models.CharField(max_length=200, null=True, verbose_name='Sayfa sayısı:')),
                ('egenote', models.FileField(null=True, upload_to='notes', verbose_name='Not Yükle:')),
                ('price', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Eklemek istediğiniz başka bir şey varsa lütfen yazınız.', max_length=1000, null=True, verbose_name='Açıklama:')),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı:')),
            ],
        ),
    ]
