# Generated by Django 2.2.5 on 2019-09-14 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egenote',
            name='user',
        ),
        migrations.AddField(
            model_name='egenote',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı:'),
        ),
    ]
