# Generated by Django 2.2.5 on 2019-09-14 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0002_auto_20190914_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egenote',
            name='user',
        ),
        migrations.AddField(
            model_name='egenote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı:'),
        ),
    ]
