# Generated by Django 2.2.5 on 2019-09-15 15:14

from django.db import migrations, models
import note.models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_egenote_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egenote',
            name='user',
        ),
        migrations.AlterField(
            model_name='egenote',
            name='egenote',
            field=models.FileField(null=True, upload_to=note.models.upload_to, verbose_name='Not Yükle:'),
        ),
    ]
