# Generated by Django 2.2.5 on 2019-09-17 14:47

from django.db import migrations, models
import django.utils.timezone
import note.models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_auto_20190915_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='egenote',
            options={'verbose_name_plural': 'Uploaded Notes'},
        ),
        migrations.AlterField(
            model_name='egenote',
            name='department',
            field=models.CharField(max_length=200, null=True, verbose_name='Department:'),
        ),
        migrations.AlterField(
            model_name='egenote',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description, Author, Content:'),
        ),
        migrations.AlterField(
            model_name='egenote',
            name='egenote',
            field=models.FileField(null=True, upload_to=note.models.upload_to, verbose_name='Upload note:'),
        ),
        migrations.AlterField(
            model_name='egenote',
            name='faculty',
            field=models.CharField(choices=[(None, 'Choose a faculty'), ('dentistry', 'Faculty of Dentistry'), ('pharmacy', 'Faculty of Pharmacy'), ('literature', 'Faculty of Literature'), ('educational', 'Faculty of Educational Sciences'), ('science', 'Faculty of Sciences'), ('arts', 'Faculty of Arts'), ('health', 'Faculty of Health Science'), ('seas', 'School of Economics and Administrative Sciences'), ('engineering', 'Faculty of Engineering'), ('medical', 'Medical Faculty'), ('law', 'Faculty of Law')], max_length=100, null=True, verbose_name='Faculty:'),
        ),
        migrations.AlterField(
            model_name='egenote',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=note.models.upload_to, verbose_name='Media:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='egenote',
            name='lecture',
            field=models.CharField(max_length=200, null=True, verbose_name='Lecture:'),
        ),
        migrations.AlterField(
            model_name='egenote',
            name='page',
            field=models.CharField(max_length=200, null=True, verbose_name='Page number:'),
        ),
    ]
